// <auto-generated />
using System;
using AccountingProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountingProject.Migrations
{
    [DbContext(typeof(PayrollDbContext))]
    [Migration("20260616232108_NormalizeAllUsersToAdmin")]
    partial class NormalizeAllUsersToAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccountingProject.Models.AnnualComparisonReportRowOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("מזהה");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("שנת_לימודים");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("נוצר_בתאריך");

                    b.Property<decimal?>("DoubleGeneral")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("הכפלה_כללית");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int")
                        .HasColumnName("מזהה_מעסיק");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("שם_מלא");

                    b.Property<string>("Grade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("דרגה");

                    b.Property<string>("InstitutionSymbol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("סמל_מוסד");

                    b.Property<bool>("IsManualEdited")
                        .HasColumnType("bit")
                        .HasColumnName("נערך_ידנית");

                    b.Property<decimal?>("JobBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("בסיס_משרה");

                    b.Property<decimal?>("JobPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("אחוז_משרה");

                    b.Property<string>("ManualEditNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("הערת_עריכה");

                    b.Property<string>("MonthCellsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("תאי_חודש_json");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("תפקיד");

                    b.Property<string>("Seniority")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ותק");

                    b.Property<int>("SlotId")
                        .HasColumnType("int")
                        .HasColumnName("מזהה_מקטע");

                    b.Property<string>("SugMisraFromPayroll")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("סוג_משרה_מעוקץ");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("עודכן_בתאריך");

                    b.Property<decimal?>("WeeklyHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("שעות_שבועיות");

                    b.HasKey("Id");

                    b.HasIndex("SlotId");

                    b.HasIndex("EmployerId", "AcademicYear", "SlotId")
                        .IsUnique();

                    b.ToTable("דריסות_דוח_השוואה_שנתי");
                });

            modelBuilder.Entity("AccountingProject.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChangesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAtUtc");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AccountingProject.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("מזהה_עובד");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("תאריך_לידה");

                    b.Property<DateOnly?>("ChildBirthDate1")
                        .HasColumnType("date")
                        .HasColumnName("תאריך_לידה_ילד_1");

                    b.Property<DateOnly?>("ChildBirthDate10")
                        .HasColumnType("date")
                        .HasColumnName("תאריך_לידה_ילד_10");

                    b.Property<DateOnly?>("ChildBirthDate2")
                        .HasColumnType("date")
                        .HasColumnName("תאריך_לידה_ילד_2");

                    b.Property<DateOnly?>("ChildBirthDate3")
                        .HasColumnType("date")
                        .HasColumnName("תאריך_לידה_ילד_3");

                    b.Property<DateOnly?>("ChildBirthDate4")
                        .HasColumnType("date")
                        .HasColumnName("תאריך_לידה_ילד_4");

                    b.Property<DateOnly?>("ChildBirthDate5")
                        .HasColumnType("date")
                        .HasColumnName("תאריך_לידה_ילד_5");

                    b.Property<DateOnly?>("ChildBirthDate6")
                        .HasColumnType("date")
                        .HasColumnName("תאריך_לידה_ילד_6");

                    b.Property<DateOnly?>("ChildBirthDate7")
                        .HasColumnType("date")
                        .HasColumnName("תאריך_לידה_ילד_7");

                    b.Property<DateOnly?>("ChildBirthDate8")
                        .HasColumnType("date")
                        .HasColumnName("תאריך_לידה_ילד_8");

                    b.Property<DateOnly?>("ChildBirthDate9")
                        .HasColumnType("date")
                        .HasColumnName("תאריך_לידה_ילד_9");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("EmployeeNumber")
                        .HasColumnType("int")
                        .HasColumnName("מספר_עובד");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int")
                        .HasColumnName("מזהה_מעסיק");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("שם_פרטי");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("מין");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("תז");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("שם_משפחה");

                    b.Property<bool?>("ManualActiveStatus")
                        .HasColumnType("bit")
                        .HasColumnName("סטטוס_פעילות_ידני");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("טל");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNumber");

                    b.HasIndex("EmployerId", "IdNumber")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("עובדים");
                });

            modelBuilder.Entity("AccountingProject.Models.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("מזהה_מעסיק");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BeneficiarySymbol")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("סמל_מוטב");

                    b.Property<string>("BusinessNumber")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("חפ");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EketzNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("מספר_עוקץ");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("שם_מעסיק");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BusinessNumber")
                        .IsUnique()
                        .HasFilter("[חפ] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("Name");

                    b.ToTable("מעסיקים");
                });

            modelBuilder.Entity("AccountingProject.Models.EmployerInstitutionSymbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("מזהה_סמל_מוסד_מעסיק");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployerId")
                        .HasColumnType("int")
                        .HasColumnName("מזהה_מעסיק");

                    b.Property<string>("InstitutionSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("סמל_מוסד");

                    b.Property<string>("InstitutionSymbolName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("שם_סמל_מוסד");

                    b.Property<string>("InstitutionType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("אחר")
                        .HasColumnName("סוג_מוסד");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId", "InstitutionSymbol")
                        .IsUnique();

                    b.ToTable("סמלי_מוסד_מעסיקים");
                });

            modelBuilder.Entity("AccountingProject.Models.EmploymentData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("מזהה_נתון_העסקה");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("שנת_לימודים");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("מזהה_עובד");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int")
                        .HasColumnName("מזהה_מעסיק");

                    b.Property<decimal?>("Grade1AgeHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("דרגה1_שעות_גיל");

                    b.Property<decimal?>("Grade1DoubleDegree")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("דרגה1_כפל_תואר");

                    b.Property<string>("Grade1Grade")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("דרגה1_דרגה");

                    b.Property<string>("Grade1GradeName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("דרגה1_שם_הדירוג");

                    b.Property<decimal?>("Grade1JobPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("דרגה1_אחוז_משרה");

                    b.Property<decimal?>("Grade1MotherBenefitPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("דרגה1_אחוז_תוספת_אם");

                    b.Property<string>("Grade1Role")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("דרגה1_תפקיד");

                    b.Property<string>("Grade1Seniority")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("דרגה1_ותק");

                    b.Property<decimal?>("Grade1Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("דרגה1_סהכ");

                    b.Property<decimal?>("Grade1TrainingBenefits")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("דרגה1_גמולי_השתלמות");

                    b.Property<decimal?>("Grade1TrainingFundPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("דרגה1_קרן_השתלמות_אחוז");

                    b.Property<decimal?>("Grade2AgeHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("דרגה2_שעות_גיל");

                    b.Property<decimal?>("Grade2DoubleDegree")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("דרגה2_כפל_תואר");

                    b.Property<string>("Grade2Grade")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("דרגה2_דרגה");

                    b.Property<string>("Grade2GradeName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("דרגה2_שם_הדירוג");

                    b.Property<decimal?>("Grade2JobPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("דרגה2_אחוז_משרה");

                    b.Property<decimal?>("Grade2MotherBenefitPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("דרגה2_אחוז_תוספת_אם");

                    b.Property<string>("Grade2Role")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("דרגה2_תפקיד");

                    b.Property<string>("Grade2Seniority")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("דרגה2_ותק");

                    b.Property<decimal?>("Grade2Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("דרגה2_סהכ");

                    b.Property<decimal?>("Grade2TrainingBenefits")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("דרגה2_גמולי_השתלמות");

                    b.Property<decimal?>("Grade2TrainingFundPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("דרגה2_קרן_השתלמות_אחוז");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.HasIndex("EmployeeId", "EmployerId", "AcademicYear")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("נתוני_העסקה");
                });

            modelBuilder.Entity("AccountingProject.Models.EmploymentDataSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("מזהה_מקטע");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmploymentDataId")
                        .HasColumnType("int")
                        .HasColumnName("מזהה_נתון_העסקה");

                    b.Property<byte>("GradeBand")
                        .HasColumnType("tinyint")
                        .HasColumnName("רמת_דרגה");

                    b.Property<string>("InstitutionSymbol")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("סמל_מוסד");

                    b.Property<decimal?>("JobBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("בסיס_משרה");

                    b.Property<byte>("SlotIndex")
                        .HasColumnType("tinyint")
                        .HasColumnName("אינדקס_מקטע");

                    b.Property<byte?>("SupplementaryParentSlotIndex")
                        .HasColumnType("tinyint")
                        .HasColumnName("מקטע_הורה_שעות_נוספות");

                    b.Property<decimal?>("WeeklyHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("שעות_שבועיות");

                    b.HasKey("Id");

                    b.HasIndex("EmploymentDataId", "GradeBand", "SlotIndex")
                        .IsUnique();

                    b.ToTable("נתוני_העסקה_מקטע");
                });

            modelBuilder.Entity("AccountingProject.Models.PayrollMonthlyInputBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("מזהה_אצווה");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("שנת_לימודים");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("נוצר_בתאריך");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("נמחק_בתאריך");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int")
                        .HasColumnName("מזהה_מעסיק");

                    b.Property<int>("GregorianYear")
                        .HasColumnType("int")
                        .HasColumnName("שנה_גרגוריאנית");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("פעיל");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("נמחק");

                    b.Property<int>("Month")
                        .HasColumnType("int")
                        .HasColumnName("חודש");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("שם_קובץ_מקורי");

                    b.Property<int>("RowsCount")
                        .HasColumnType("int")
                        .HasColumnName("מספר_שורות");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("עודכן_בתאריך");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("הועלה_בתאריך");

                    b.Property<string>("UploadedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("הועלה_על_ידי");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId", "AcademicYear", "Month", "GregorianYear")
                        .IsUnique()
                        .HasFilter("[פעיל] = 1 AND [נמחק] = 0");

                    b.ToTable("קלט_עוקץ_חודשי_אצווה");
                });

            modelBuilder.Entity("AccountingProject.Models.PayrollMonthlyInputRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("מזהה_שורה");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("שנת_לימודים");

                    b.Property<decimal?>("AgeHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("שעות_גיל");

                    b.Property<int>("BatchId")
                        .HasColumnType("int")
                        .HasColumnName("מזהה_אצווה");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("נוצר_בתאריך");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("נמחק_בתאריך");

                    b.Property<decimal?>("DoubleDegree")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("כפל_תואר");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int")
                        .HasColumnName("מזהה_מעסיק");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("שם_מלא");

                    b.Property<decimal?>("GeneralMultiplier")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("הכפלה_כללית");

                    b.Property<string>("Grade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("דרגה");

                    b.Property<int>("GregorianYear")
                        .HasColumnType("int")
                        .HasColumnName("שנה_גרגוריאנית");

                    b.Property<string>("IdNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("תז");

                    b.Property<string>("InstitutionSymbol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("סמל_מוסד");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("נמחק");

                    b.Property<bool>("IsManualEdited")
                        .HasColumnType("bit")
                        .HasColumnName("נערך_ידנית");

                    b.Property<decimal?>("JobBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("בסיס_משרה");

                    b.Property<decimal?>("JobPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("אחוז_משרה");

                    b.Property<string>("ManualEditNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("הערת_עריכה_ידנית");

                    b.Property<int>("Month")
                        .HasColumnType("int")
                        .HasColumnName("חודש");

                    b.Property<string>("OketzEmployeeNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("מספר_עובד_בעוקץ");

                    b.Property<string>("RawCellsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("תאים_גולמיים_json");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("תפקיד");

                    b.Property<decimal?>("Seniority")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ותק");

                    b.Property<int?>("SourceExcelRowNumber")
                        .HasColumnType("int")
                        .HasColumnName("מספר_שורה_באקסל");

                    b.Property<decimal?>("TrainingBenefits")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("גמולי_השתלמות");

                    b.Property<decimal?>("TrainingFund")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("קרן_השתלמות");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("עודכן_בתאריך");

                    b.Property<decimal?>("WeeklyHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("שעות_שבועיות");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("IdNumber");

                    b.HasIndex("InstitutionSymbol");

                    b.HasIndex("OketzEmployeeNumber");

                    b.HasIndex("EmployerId", "AcademicYear", "Month", "GregorianYear");

                    b.ToTable("קלט_עוקץ_חודשי_שורה");
                });

            modelBuilder.Entity("AccountingProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AccountingProject.Models.AnnualComparisonReportRowOverride", b =>
                {
                    b.HasOne("AccountingProject.Models.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccountingProject.Models.EmploymentDataSlot", "Slot")
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("AccountingProject.Models.Employee", b =>
                {
                    b.HasOne("AccountingProject.Models.Employer", "Employer")
                        .WithMany("Employees")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("AccountingProject.Models.EmployerInstitutionSymbol", b =>
                {
                    b.HasOne("AccountingProject.Models.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("AccountingProject.Models.EmploymentData", b =>
                {
                    b.HasOne("AccountingProject.Models.Employee", "Employee")
                        .WithMany("EmploymentData")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccountingProject.Models.Employer", "Employer")
                        .WithMany("EmploymentData")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("AccountingProject.Models.EmploymentDataSlot", b =>
                {
                    b.HasOne("AccountingProject.Models.EmploymentData", "EmploymentData")
                        .WithMany("Slots")
                        .HasForeignKey("EmploymentDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmploymentData");
                });

            modelBuilder.Entity("AccountingProject.Models.PayrollMonthlyInputBatch", b =>
                {
                    b.HasOne("AccountingProject.Models.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("AccountingProject.Models.PayrollMonthlyInputRow", b =>
                {
                    b.HasOne("AccountingProject.Models.PayrollMonthlyInputBatch", "Batch")
                        .WithMany("Rows")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("AccountingProject.Models.Employee", b =>
                {
                    b.Navigation("EmploymentData");
                });

            modelBuilder.Entity("AccountingProject.Models.Employer", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("EmploymentData");
                });

            modelBuilder.Entity("AccountingProject.Models.EmploymentData", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("AccountingProject.Models.PayrollMonthlyInputBatch", b =>
                {
                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
