// <auto-generated />
using System;
using AccountingProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountingProject.Migrations
{
    [DbContext(typeof(PayrollDbContext))]
    [Migration("20260420171110_FixAuditLogIdToInt")]
    partial class FixAuditLogIdToInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccountingProject.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChangesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAtUtc");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AccountingProject.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("מזהה_עובד");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("תאריך_לידה");

                    b.Property<DateOnly?>("ChildBirthDate1")
                        .HasColumnType("date")
                        .HasColumnName("תאריך_לידה_ילד_1");

                    b.Property<DateOnly?>("ChildBirthDate10")
                        .HasColumnType("date")
                        .HasColumnName("תאריך_לידה_ילד_10");

                    b.Property<DateOnly?>("ChildBirthDate2")
                        .HasColumnType("date")
                        .HasColumnName("תאריך_לידה_ילד_2");

                    b.Property<DateOnly?>("ChildBirthDate3")
                        .HasColumnType("date")
                        .HasColumnName("תאריך_לידה_ילד_3");

                    b.Property<DateOnly?>("ChildBirthDate4")
                        .HasColumnType("date")
                        .HasColumnName("תאריך_לידה_ילד_4");

                    b.Property<DateOnly?>("ChildBirthDate5")
                        .HasColumnType("date")
                        .HasColumnName("תאריך_לידה_ילד_5");

                    b.Property<DateOnly?>("ChildBirthDate6")
                        .HasColumnType("date")
                        .HasColumnName("תאריך_לידה_ילד_6");

                    b.Property<DateOnly?>("ChildBirthDate7")
                        .HasColumnType("date")
                        .HasColumnName("תאריך_לידה_ילד_7");

                    b.Property<DateOnly?>("ChildBirthDate8")
                        .HasColumnType("date")
                        .HasColumnName("תאריך_לידה_ילד_8");

                    b.Property<DateOnly?>("ChildBirthDate9")
                        .HasColumnType("date")
                        .HasColumnName("תאריך_לידה_ילד_9");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("EmployeeNumber")
                        .HasColumnType("int")
                        .HasColumnName("מספר_עובד");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("שם_פרטי");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("מין");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("תז");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("שם_משפחה");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("טל");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNumber");

                    b.HasIndex("IdNumber")
                        .IsUnique();

                    b.ToTable("עובדים");
                });

            modelBuilder.Entity("AccountingProject.Models.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("מזהה_מעסיק");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessNumber")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("חפ");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EketzNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("מספר_עוקץ");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("שם_מעסיק");

                    b.Property<string>("PayrollNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("מספר_שכר");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BusinessNumber")
                        .IsUnique()
                        .HasFilter("[חפ] IS NOT NULL");

                    b.HasIndex("Name");

                    b.ToTable("מעסיקים");
                });

            modelBuilder.Entity("AccountingProject.Models.EmploymentData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("מזהה_נתון_העסקה");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AgeHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("שעות_גיל");

                    b.Property<decimal?>("ClassEducationBonus")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("גמול_חינוך_כיתה");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("DoubleDegree")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("כפל_תואר");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("מזהה_עובד");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int")
                        .HasColumnName("מזהה_מעסיק");

                    b.Property<decimal?>("G1FromHours1")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("מתוך_שעות_משרה_1_דרוג_1");

                    b.Property<decimal?>("G1Hours1")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("שעות_משרה_1_דרוג_1");

                    b.Property<decimal?>("G1Hours2")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("שעות_משרה_2_דרוג_1");

                    b.Property<decimal?>("G1Hours3")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("שעות_משרה_3_דרוג_1");

                    b.Property<decimal?>("G2FromHours1")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("מתוך_שעות_משרה_1_דרוג_2");

                    b.Property<decimal?>("G2Hours1")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("שעות_משרה_1_דרוג_2");

                    b.Property<decimal?>("G2Hours2")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("שעות_משרה_2_דרוג_2");

                    b.Property<decimal?>("G2Hours3")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("שעות_משרה_3_דרוג_2");

                    b.Property<decimal?>("GeneralMultiplierPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("הכפלה_כללית_באחוז");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("דירוג");

                    b.Property<string>("GradeName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("שם_הדירוג");

                    b.Property<string>("InstitutionSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("סמל_מוסד");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("סוג_משרה");

                    b.Property<decimal?>("MotherSupplementPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("אחוז_תוספת_אם");

                    b.Property<decimal?>("PensionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("פנסיה_סכום");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("תפקיד");

                    b.Property<int>("SalaryMonth")
                        .HasColumnType("int")
                        .HasColumnName("חודש");

                    b.Property<int>("SalaryYear")
                        .HasColumnType("int")
                        .HasColumnName("שנה");

                    b.Property<string>("Seniority")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ותק");

                    b.Property<decimal?>("TrainingBonuses")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("גמולי_השתלמות");

                    b.Property<decimal?>("TrainingFundAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("קרן_השתלמות_סכום");

                    b.Property<decimal?>("TrainingFundPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("קרן_השתלמות_אחוז");

                    b.Property<decimal?>("TrainingProfessionBonus")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("גמול_הכשרה_ומקצוע");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId", "SalaryYear", "SalaryMonth");

                    b.HasIndex("EmployeeId", "EmployerId", "SalaryYear", "SalaryMonth");

                    b.ToTable("נתוני_העסקה");
                });

            modelBuilder.Entity("AccountingProject.Models.EmploymentData", b =>
                {
                    b.HasOne("AccountingProject.Models.Employee", "Employee")
                        .WithMany("EmploymentData")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccountingProject.Models.Employer", "Employer")
                        .WithMany("EmploymentData")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("AccountingProject.Models.Employee", b =>
                {
                    b.Navigation("EmploymentData");
                });

            modelBuilder.Entity("AccountingProject.Models.Employer", b =>
                {
                    b.Navigation("EmploymentData");
                });
#pragma warning restore 612, 618
        }
    }
}
